config/routes.rb
Rails.application.routes.draw do
  get 'restaurants/new', as: :new_restaurant
  post 'restaurants', to: 'restaurants#create'
  get 'restaurants', to: 'restaurants#index'
  get 'restaurants/:id', to: 'restaurants#show', as: :restaurant
  get 'restaurants/:id/edit', to: 'restaurants#edit', as: :edit_restaurant
  patch 'restaurants/:id', to: 'restaurants#update'
  delete 'restaurants/:id', to: 'restaurants#destroy', as: :delete_restaurant
  get 'restaurants/:id/reviews/new', to: 'reviews#new'
  root 'restaurants#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: ['chinese', 'italian', 'japanese', 'french', 'belgian'] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true, inclusion: { in: 0..5 }
  validates :rating, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    set_restaurant
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to @restaurant
    else
      render :new
    end
  end

  def edit
    @restaurant = set_restaurant
  end

  def update
    @restaurant = set_restaurant
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant
    else
      render :new
    end
  end

  def destroy
    @restaurant = set_restaurant
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :category, :address, :phone_number)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-4 col-sm-offset-4">
      <%= simple_form_for(@restaurant) do |f|%>
      <div class="form-inputs">
        <%= f.input :name %>
        <%= f.input :category %>
        <%= f.input :address %>
        <%= f.input :phone_number %>
      </div>
      <div class="form-actions">
        <%= f.button :submit %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/restaurants/edit.html.erb
<%= render 'form' %>

app/views/restaurants/index.html.erb
<h1 class="text-center">All the restaurants</h1>
<div class="text-center">
<%= link_to "Add new restaurant", new_restaurant_path, class: "btn btn-primary" %>
</div>
<div class="container">
  <div class="row">
    <% @restaurants.each do |resto| %>
    <%= link_to restaurant_path(resto) do  %>
    <div class="col-sm-4 text-center resto-card">
      <h2>
        <%= resto.name %>
      </h2>
      <p>
        <%= resto.category %>
      </p>
      <p>
        <%= resto.address %>
      </p>
    </div>
    <% end %>
    <% end %>
  </div>
</div>

app/views/restaurants/new.html.erb
<%= render 'form' %>

app/views/restaurants/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 col-sm-offset-4">
      <h1 class="text-center"><%= @restaurant.name %>
      </h1>
      <p>Category: <%= @restaurant.category %></p>
      <p>Address: <%= @restaurant.address %></p>
      <p>Phone number: <%= @restaurant.phone_number %></p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus consectetur incidunt tempora placeat esse possimus doloremque, quo explicabo voluptatum quisquam ad? Dolor iusto eum debitis veritatis labore officiis amet rem.</p>

      <div class="text-center">
        <%= link_to "Back", restaurants_path, class: "btn btn-primary"  %>
        <%= link_to "Edit", edit_restaurant_path(@restaurant), class: "btn btn-warning" %>
        <%= link_to "Delete", delete_restaurant_path(@restaurant), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"  %>
        <%= link_to "Add a review", new_review_path(@restaurant), class: "btn btn-info"  %>
       </div>
    </div>
  </div>
</div>

app/views/reviews/_form.html.erb
<%= simple_form_for([@restaurant, @review]) do |f| %>
<%= f.input :content %>
<%= f.input :rating %>
<%= f.button :submit %>
<% end %>

app/views/reviews/new.html.erb
<%= render 'form' %>